### ISSUE TITLE
Install package with RAD Studio 10.1 Berlin (starter edition -> only C++builder , not Delphi)

### ISSUE THREAD

**Issue by ModbusOli** [coassoftwaresystems/delphi-modbus#11]
Hi,
I have a problem for installing the Modbus package under a RAD Studio 10.1 Berlin (Starter edition -> only  C++Builder 10.1 Berlin , not Delphi): I cannot do the installation as I don't have the Delphi Berlin.
The RAD ide complains with the "Delphi.Personality".
I try to use dcc32 comand line but I am not at all an expert and I fail.
Any chance to have somebody to compile the designtime and the runtime in "bpl" packages for C++Builder  Berlin 10.1? I will appreciate a lot.
Thanks
Best Regards
Olivier

**Comment by plpolak** [comment]
I have no experience on C++ builder, so when anyone can provide the correct packages, I can include them.

**Comment by Daijobou** [comment]
I have the same issue with Rad Studio 2009, when you start only C++Builder. This component can only add with Delphi. :(
