### ISSUE TITLE
Wrong Indy versions in source

### ISSUE THREAD

**Issue by Daijobou** [coassoftwaresystems/delphi-modbus#14]
DelphiModbus2009.dpk says

```
requires
  rtl,
  IndyCore,
  IndyProtocols,
  IndySystem;

```

thats wrong. See http://www.indyproject.org/Sockets/Docs/Indy10Installation.de.aspx

D/CB/RAD 2009 is with extension 120, means IndyCore120 and so on.

**Comment by plpolak** [comment]
Weird as the Delphi compiler does not require this. I do not have C++ builder. Maybe it is related to the 2009 version?

**Comment by Daijobou** [comment]
> Maybe it is related to the 2009 version?

I can only says thats it comile only with "120"-extension in Rad Studio 2009. ;)
