### ISSUE TITLE
Compiler error E2370 with TIdModBusServer.hpp

### ISSUE THREAD

**Issue by Daijobou** [coassoftwaresystems/delphi-modbus#17]
This is possible a RAD Studio 2009 (C++Builder) compiler bug, in Rad Studio Berlin its working fine. I add this ticket only for Google. Compile a project with TIdModBusServer, I get two errors:

[BCC32 Error] IdModBusServer.hpp(120): E2370
[BCC32 Error] IdModBusServer.hpp(121): E2370

Line 120:  __property TModBusCoilWriteEvent OnWriteCoils = {read=FOnWriteCoils, write=FOnWriteCoils}; 
Line 121:  __property TModBusRegisterWriteEvent OnWriteRegisters = {read=FOnWriteRegisters, write=FOnWriteRegisters};

A maybe workaround is, to move this two lines in header-file in the next **public:** section. After this I can compile the project without a error. I can't tell the reason, but here is maybe a problem with convertion fixed-size arrays?

**Comment by BugsDigger** [comment]
Simply comment out "const" in generated declarations:

typedef void __fastcall (__closure *TModBusCoilWriteEvent)
(const Idcontext::TIdContext* Sender, const int RegNr, const int Count,
 Byte /*const*/ * Data,  // here
 const Modbustypes::TModBusRequestBuffer &RequestBuffer, Byte &ErrorCode);

and

typedef void __fastcall (__closure *TModBusRegisterWriteEvent)
(const Idcontext::TIdContext* Sender, const int RegNr, const int Count,
 Word /*const*/ * Data, // here
 const Modbustypes::TModBusRequestBuffer &RequestBuffer, Byte &ErrorCode);
