### ISSUE TITLE
Adding IP of Modbus sensor

### ISSUE THREAD

**Issue by urosv** [coassoftwaresystems/delphi-modbus#20]
How can we use this component to connect to modbus sensor. Bindings are readonly, adding IP at adding at runtime is readonly ? Shows registers on localhost which is not modbus client ? Any howto exists ?

**Comment by plpolak** [comment]
When using TIdModusClient, set the Host (and optionally the Port) property.

**Comment by urosv** [comment]
If i'm correct there is no demo inside the packege covering "client" mode?

**Comment by plpolak** [comment]
The Modbus protocol uses the term 'Master' for a client. The Master demo shows how the use the client component.
