### ISSUE TITLE
Registering Components...

### ISSUE THREAD

**Issue by Nuzzi** [coassoftwaresystems/delphi-modbus#26]
Great tools, folks.  Thank you!  I am having a problem getting the components to show up in the Tool Palette.  I load the DPK, compile both projects, install and it says it installs fine.  If I check the packages under Options it shows up fine and lists both components, but neither component shows up in the Tool Palette.  Any suggestions? This is in Berlin (10.1) and Tokyo (10.2) RAD Studio (using with C++).

**Comment by Nuzzi** [comment]
I think I just answered my own question. Interesting.  if I have a Delphi project, it shows up fine.  I will create a C++ project and register and see how that goes.

**Comment by Daijobou** [comment]
Same here. Successful compiled in Rad Studio 2009 Professional Delphi+C++, but only in Delphi its in tool-palette. In C++Builder its not appear, but old projects have it in forms.

How I get the components in tool-palette for C++Builder?
