### ISSUE TITLE
ModBusClient.ReadHoldingRegisters - Amount

### ISSUE THREAD

**Issue by faber33** [coassoftwaresystems/delphi-modbus#45]
Hi. How many registers can be read at once? 

So far I can read up to 126 registers. Is this a limit or a bug in my program?

**Comment by plpolak** [comment]
According to the Modbus specification, there is a limit of 126 registers when reading the hold registers. Unfortunately the protocol specifies the amount in a word, suggesting it is possible to read more in one go.

[Modbus protocol specification](https://www.modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf)
