### ISSUE TITLE
Runtime error 216

### ISSUE THREAD

**Issue by JeanYvesJonet** [coassoftwaresystems/delphi-modbus#50]
Hello,
I installed the package for delphi 10.4, it's OK.
But when i use client on my form, the programm build with no error, and at the beginning of run i have an error runtime 216.
I tried some solutions, but always this error.
The same code compiled with delphi 10.2 and modbus V1.6.7 is running without error.
Thanks

**Comment by JensMertelmeyer** [comment]
Runtime Error 216 is an access violation. You have a debugger. Where does the access violation occur?

**Comment by JeanYvesJonet** [comment]
Hello,
I re-installed the package after update informations about ToolsAPI , it seems to be worked normally.
Thanks for your help.
