### ISSUE TITLE
XE11 Alexandria 

### ISSUE THREAD

**Issue by penengo** [coassoftwaresystems/delphi-modbus#51]
Does have Someone the Xe11 Alexandria Porting?
Thank you

**Comment by slazzariny** [comment]
I was able to install this library in Delphi 11 by bundling a change in the ModBusCompiler.inc file.
It works for me.
I hope the developers will make the corresponding changes to this version of Delphi.
[Moddelphi11.zip](https://github.com/coassoftwaresystems/delphi-modbus/files/7357527/Moddelphi11.zip)
