### ISSUE TITLE
Update ModBusCompiler.inc

### ISSUE THREAD

**Issue by Crayon2000** [coassoftwaresystems/delphi-modbus#6]
Hello, since RAD Studio 10.1 Berlin is now available the *ModBusCompiler.inc* must be updated.
The compiler version is **VER310** (http://docwiki.embarcadero.com/RADStudio/en/Compiler_Versions)

In my code I have added this temporary fix in order to compile the library:
```
{$IFDEF VER310}
  {$DEFINE DMB_DELPHI1}
  {$DEFINE DMB_DELPHI2}
  {$DEFINE DMB_DELPHI3}
  {$DEFINE DMB_DELPHI4}
  {$DEFINE DMB_DELPHI5}
  {$DEFINE DMB_DELPHI6}
  {$DEFINE DMB_DELPHI7}
  {$DEFINE DMB_DELPHI2005}
  {$DEFINE DMB_DELPHI2006}
  {$DEFINE DMB_DELPHI2007}
  {$DEFINE DMB_DELPHI2009}
  {$DEFINE DMB_DELPHI2010}
  {$DEFINE DMB_DELPHIXE}
  {$DEFINE DMB_DELPHIXE2}
  {$DEFINE DMB_DELPHIXE3}
  {$DEFINE DMB_DELPHIXE4}
  {$DEFINE DMB_DELPHIXE5}
  {$DEFINE DMB_DELPHIXE6}
  {$DEFINE DMB_DELPHIXE7}
  {$DEFINE DMB_DELPHIXE8}
  {$DEFINE DMB_DELPHI10_SEATTLE}
  {$DEFINE DMB_DELPHI10_1_BERLIN}
  {$DEFINE DMB_DELPHI10_1_BERLIN_ONLY}
{$ENDIF}
```

I didn't do a Pull Request because I'm not sure if you want to use DMB_DELPHI10_1_BERLIN or DMB_DELPHI101_BERLIN (no underscore before the 1).

**Comment by plpolak** [comment]
I have accepted your change in the develop branch. I haven't installed the 10.1 Berlin release yet, but will add dedicated packages for it.
