### ISSUE TITLE
License information needs to be added

### ISSUE THREAD

**Issue by debiesur** [coassoftwaresystems/delphi-modbus#67]
Please add a license to your project in the overview. I found it in the sources but it would be nice to have it directly at hand. Even though you write a very permissive text I'd recommend to use MIT license this is known and easy to handle without a legal background.

**Comment by JensMertelmeyer** [comment]
I think the intention is that Github "knows" what license is applied, so you can immediately see on the front page, or filter repos by license, ...

![image](https://github.com/user-attachments/assets/a34e3e8e-40f0-4b4c-819e-13b120ebef97)


https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by plpolak** [comment]
I moved the license file to the root of the repo, and now it is recognized by GitHub
